// import express ... 
const express = require('express')

// create the express app ... 
const app = express()
// use json to read and write data ...
app.use(express.json())

// import routes ...
require('./app/routes.js')(app)

// check if the app is working by defining a simple route ...
app.get('/', (req, res)=>{
    res.json({"message": "Welcome to my Express App using MySQL"})
})

// listen for requests and start the server ...
app.listen(4300, ()=>{
    console.log("Server listening to port number 4300 now")
})

// insert data into the table ... 
